name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: app/build/outputs/apk/debug/app-debug.apk
        body: |
          Automated release of the Vivo Booster app.
          Install the app-debug.apk file below.
