name: Build Android APK

on:
  push:
    branches:
      - main
    # --- THIS IS THE KEY CHANGE ---
    # The build will now ONLY run if app/build.gradle is changed.
    paths:
      - 'app/build.gradle'

jobs:
  build:
    # We can add an 'if' condition here for even more control.
    # This checks if the commit message contains '[build]'.
    # So you need to change the file AND use the keyword.
    if: contains(github.event.head_commit.message, '[build]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Gradle
      # Cache is now enabled by default because we removed 'cache-disabled'.
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: app/build/outputs/apk/debug/app-debug.apk
        body: |
          Automated release of the Vivo Booster app.
          Install the app-debug.apk file below.
